#!/usr/bin/env bash
# MakeKeeper — one-line installer / updater.
#
#   Install:  curl -fsSL https://raw.githubusercontent.com/makekeeper/makekeeper/main/deploy/install.sh | bash
#   Update:   re-run the same line, or:  ./install.sh --update
#
# Idempotent: an existing .env is preserved (never overwrites your secrets); it
# always pulls the newest images and (re)starts the stack. DB migrations are
# applied automatically by the app container on start. See ../INSTALL.md.
set -euo pipefail

# ── Config (override via env) ───────────────────────────────────────────────
GH_OWNER="${MK_GH_OWNER:-makekeeper}"          # GitHub owner of the ghcr packages / repo
GH_REPO="${MK_GH_REPO:-makekeeper}"
GH_BRANCH="${MK_GH_BRANCH:-main}"
RAW_BASE="${MK_RAW_BASE:-https://raw.githubusercontent.com/${GH_OWNER}/${GH_REPO}/${GH_BRANCH}/deploy}"
INSTALL_DIR="${MK_DIR:-./makekeeper}"
COMPOSE_FILE="docker-compose.prod.yml"

UPDATE=0
[ "${1:-}" = "--update" ] && UPDATE=1

log()  { echo "  ➜ $*"; }
err()  { echo "  ✗ $*" >&2; }
die()  { err "$*"; exit 1; }

# ── Prerequisites ───────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "docker is not installed. See https://docs.docker.com/engine/install/"
if docker compose version >/dev/null 2>&1; then
  DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  DC="docker-compose"
else
  die "docker compose v2 is required (or legacy docker-compose)."
fi

# Downloader (curl or wget) — for the compose file.
if command -v curl >/dev/null 2>&1; then
  fetch() { curl -fsSL "$1" -o "$2"; }
elif command -v wget >/dev/null 2>&1; then
  fetch() { wget -qO "$2" "$1"; }
else
  die "need curl or wget to download the compose file."
fi

# Secret generator (>=32 chars, url-safe).
gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr '+/' '-_' | tr -d '=\n'
  elif command -v node >/dev/null 2>&1; then
    node -e "console.log(require('crypto').randomBytes(48).toString('base64url'))"
  else
    die "need openssl or node to generate secrets."
  fi
}

echo "════════════════════════════════════════"
echo "  MakeKeeper — installer"
echo "════════════════════════════════════════"

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# ── Compose file (refresh to latest, unless told to keep the local one) ──────
# update.sh sets MK_SKIP_COMPOSE_FETCH=1 to reuse the already-deployed file
# (offline, no MK_GH_OWNER needed); a fresh install always downloads it.
if [ "${MK_SKIP_COMPOSE_FETCH:-0}" = "1" ] && [ -f "$COMPOSE_FILE" ]; then
  log "Using existing ${COMPOSE_FILE}."
else
  log "Downloading ${COMPOSE_FILE}…"
  fetch "${RAW_BASE}/${COMPOSE_FILE}" "$COMPOSE_FILE" \
    || die "failed to download ${RAW_BASE}/${COMPOSE_FILE} (check MK_GH_OWNER)."
fi

# ── .env (generate once, then preserve) ─────────────────────────────────────
if [ -f .env ]; then
  log ".env already present — keeping your existing secrets."
  # Installs predating the install-method marker have no MK_INSTALL_METHOD; the
  # compose default would then report them as a plain `compose` install. Append
  # it (never rewrite the file) so an upgrade reports its real origin.
  if ! grep -q '^MK_INSTALL_METHOD=' .env; then
    printf '\n# How this instance was installed — a diagnostic shown in Settings → Updates.\nMK_INSTALL_METHOD=install-sh\n' >> .env
    log "Stamped MK_INSTALL_METHOD=install-sh into your existing .env."
  fi
else
  [ "$UPDATE" = "1" ] && die "--update requested but no .env found in ${INSTALL_DIR}."
  log "Generating .env with fresh secrets…"
  umask 077
  cat > .env <<EOF
# Generated by install.sh — keep this file safe and backed up.
# APP_SECRET encrypts stored secrets at rest; changing it invalidates them.
TAG=latest
IMAGE_APP=ghcr.io/${GH_OWNER}/app
IMAGE_WEB=ghcr.io/${GH_OWNER}/web
PUBLIC_WEB_PORT=8080
POSTGRES_USER=makekeeper
POSTGRES_DB=makekeeper
# How this instance was installed — a diagnostic shown in Settings → Updates.
MK_INSTALL_METHOD=install-sh
POSTGRES_PASSWORD=$(gen_secret)
APP_SECRET=$(gen_secret)
JWT_SECRET=$(gen_secret)
# PUBLIC_BASE_URL=https://your.domain
EOF
  log ".env created."
fi

# shellcheck disable=SC1091
set -a; . ./.env; set +a
PORT="${PUBLIC_WEB_PORT:-8080}"

# ── Bring the stack up ──────────────────────────────────────────────────────
log "Pulling images…"
$DC -f "$COMPOSE_FILE" pull
log "Starting stack…"
$DC -f "$COMPOSE_FILE" up -d

# ── Wait for readiness ──────────────────────────────────────────────────────
log "Waiting for the app to become ready (migrations run on first boot)…"
ready=0
for _ in $(seq 1 60); do
  if command -v curl >/dev/null 2>&1; then
    curl -fsS "http://localhost:${PORT}/api/health/ready" >/dev/null 2>&1 && { ready=1; break; }
  else
    wget -qO- "http://localhost:${PORT}/api/health/ready" >/dev/null 2>&1 && { ready=1; break; }
  fi
  sleep 3
done

echo "════════════════════════════════════════"
if [ "$ready" = "1" ]; then
  echo "  ✓ MakeKeeper is up!"
  echo "  Open: http://localhost:${PORT}"
else
  echo "  ⚠ Stack started but readiness not confirmed yet."
  echo "  Check logs: (cd ${INSTALL_DIR} && ${DC} -f ${COMPOSE_FILE} logs -f app)"
fi
echo "════════════════════════════════════════"
