// The MakeKeeper mark, as geometry rather than as a file (#260).
//
// The source artwork (`apps/frontend/public/icons/logo-mono.svg`) is a 6×6
// pixel grid with 21 filled cells, shipped with a hardcoded `#111111` and an
// uneven 1/3.6-unit padding. Neither survives contact with this app: the mark
// has to repaint with the active colour scheme (#236), which an `<img>` cannot
// do, and it has to sit optically centred at 20px in the collapsed rail.
//
// So the cells live here, once, and everything else is derived from them:
// `BrandMark.vue` renders them into the cascade (`currentColor`), and
// `brandMarkSvg()` serialises them for the surfaces that render OUTSIDE it —
// the favicon and the PWA icons, generated by
// `tools/brand/generate-brand-assets.mjs`, which imports this module rather
// than restating the grid.

/** A filled cell of the mark's grid, as `[column, row]`, both 0-indexed. */
export type BrandMarkCell = readonly [column: number, row: number];

/** Cells per side — the mark is a square grid. */
export const BRAND_MARK_GRID = 6;

/** Grid pitch in viewBox units (cell + gutter). */
export const BRAND_MARK_PITCH = 8;

/** Painted size of one cell; the 0.6-unit remainder is the gutter. */
export const BRAND_MARK_CELL = 7.4;

/**
 * Side of the mark's own box: the grid, cropped to the painted cells. The
 * source's uneven padding is dropped here — padding is the container's job
 * (the tile), so the glyph itself is flush and therefore centred by anything
 * that centres a square.
 */
export const BRAND_MARK_SIZE =
  BRAND_MARK_PITCH * (BRAND_MARK_GRID - 1) + BRAND_MARK_CELL;

export const BRAND_MARK_CELLS: readonly BrandMarkCell[] = [
  [2, 0],
  [3, 0],
  [4, 0],
  [1, 1],
  [2, 1],
  [3, 1],
  [4, 1],
  [0, 2],
  [1, 2],
  [3, 2],
  [4, 2],
  [1, 3],
  [2, 3],
  [3, 3],
  [4, 3],
  [5, 3],
  [1, 4],
  [2, 4],
  [3, 4],
  [1, 5],
  [3, 5],
];

/**
 * The brand lockup as standalone SVG markup: a coloured tile with the mark
 * knocked out of it in white — the same treatment every in-app surface wears,
 * so the browser tab and the installed app icon do not read as a second brand.
 *
 * `accent` is a CSS colour supplied by the caller, never a palette copy kept
 * here. The generator passes the brand's own colour, which is what an icon
 * outside the app wears; inside the app `BrandMark.vue` takes the active
 * scheme's accent straight from the cascade instead.
 */
export function brandMarkSvg(options: {
  accent: string;
  /** Tile corner radius as a fraction of the tile's side. */
  radius?: number;
  /** Share of the tile's side left free around the glyph, per edge. */
  padding?: number;
}): string {
  const { accent, radius = 0.22, padding = 0.185 } = options;
  const box = 64;
  const inset = box * padding;
  const scale = (box - inset * 2) / BRAND_MARK_SIZE;
  const cells = BRAND_MARK_CELLS.map(
    ([column, row]) =>
      `<rect x="${column * BRAND_MARK_PITCH}" y="${row * BRAND_MARK_PITCH}" ` +
      `width="${BRAND_MARK_CELL}" height="${BRAND_MARK_CELL}"/>`,
  ).join('');
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${box} ${box}">` +
    `<rect width="${box}" height="${box}" rx="${box * radius}" fill="${accent}"/>` +
    `<g fill="#ffffff" transform="translate(${inset} ${inset}) scale(${scale})">${cells}</g>` +
    `</svg>`
  );
}
